---

- hosts: graphite
  become: true
  roles: 
    - monitor/graphite

- hosts: osds,mdss,clients
  become: true
  roles:
    - monitor/collectl

- hosts: mdss
  become: true
  roles:
    - ceph/ceph-stats
  tasks:
    - pause: minutes=5
