---
- hosts: clients[0]
  become: true
  tasks:

  - set_fact: output="/popper/results/summary.txt"
  - set_fact: args="--rm -w /root -v {{ root_src }}:/root -v /etc/ceph:/etc/ceph --entrypoint=root --volumes-from cephfs rootproject/root-ubuntu16 -b -q"

  - file:
     path: "/etc/ceph"
     mode: 0777
     state: "directory"

  - copy:
      src:  "{{ root_src }}/{{ item }}"
      dest: "/etc/ceph/{{ item }}" 
      mode: 0777
    with_items:
    - ["{{ root_file }}", "cmsdump.outerr", "branchListFile.txt"]

  - shell: docker exec cephfs rm -rf {{ mount_point }}/{{ item }}
    ignore_errors: true
    with_items:
    - ["namespace", "{{ root_file }}"]

  - name: setup 3 - write the ROOT file into CephFS
    shell: docker exec cephfs cp /etc/ceph/{{ root_file }} {{ mount_point }}/{{ root_file }}
    register: r
  - local_action: lineinfile dest="{{ output }}" line="write_cephfs,{{ r.delta }},{{ ansible_date_time.time }}" create="yes"
  - shell: docker exec cephfs chmod 777 -R {{ mount_point }}/{{ root_file }}

  - name: setup 3 - read the ROOT file from CephFS
    shell: docker run {{ args }} \
             .x root/src/read_baskets_from_file_hep_method.cpp\(\"{{ mount_point }}/{{ root_file }}\",\"/etc/ceph/branchListFile.txt\"\)
    register: r
  - local_action: lineinfile dest="{{ output }}" line="read_cephfs,{{ r.delta }},{{ ansible_date_time.time }}" create="yes"

  - name: setup 4 - write namespace from ROOT file
    shell: docker run {{ args }} \
             .x root/src/write_baskets_to_file.cpp\(\"/etc/ceph/2AC36403-8E7E-E711-A599-02163E01366D.root\",\"{{ mount_point }}/namespace\"\)
    register: r
  - local_action: lineinfile dest="{{ output }}" line="write_fpb_cephfs,{{ r.delta }},{{ ansible_date_time.time }}" create="yes"

  - name: setup 4 - read branches from ROOT namespace
    shell: docker run {{ args }} \
             .x root/src/read_baskets_from_file_our_method.cpp\(\"/etc/ceph/branchListFile.txt\"\,\"{{ mount_point }}/namespace\"\)
    register: r
  - local_action: lineinfile dest="{{ output }}" line="read_fpb_cephfs,{{ r.delta }},{{ ansible_date_time.time }}" create="yes"
